remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 

title: ProxyForge
description: Solving IP Throttling with Rotating Proxies

author:
  name: tbhaxor
  email: tbhaxor@gmail.com

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/tbhaxor/ProxyForge"
    - platform: twitter
      user_url: "https://twitter.com/@tbhaxor"
